# Generated by Django 4.2 on 2025-01-25 10:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0003_message_is_seen'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='created_user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='created_chatrooms', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
